import os
import time
from abc import ABC, abstractmethod

import openai
from django.conf import settings


class BaseLLMService(ABC):
    @abstractmethod
    def generate_care_plan(self, order, patient) -> str:
        pass


class OpenAIService(BaseLLMService):
    def generate_care_plan(self, order, patient) -> str:
        client = openai.OpenAI(api_key=settings.OPENAI_API_KEY)

        prompt = f"""You are a clinical pharmacist. Generate a professional care plan for this patient.

Patient Information:
- Name: {patient.first_name} {patient.last_name}
- MRN: {patient.mrn}
- Primary Diagnosis: {order.primary_diagnosis}
- Medication: {order.medication_name}
- Patient Records: {order.patient_records}

Generate a care plan with these sections:
1. Problem List / Drug Therapy Problems (DTPs)
2. Goals (SMART)
3. Pharmacist Interventions / Plan
4. Monitoring Plan & Lab Schedule

Be specific and clinical."""

        response = client.chat.completions.create(
            model='gpt-4o',
            messages=[{'role': 'user', 'content': prompt}],
            max_tokens=1024,
        )
        return response.choices[0].message.content


class MockService(BaseLLMService):
    def generate_care_plan(self, order, patient) -> str:
        time.sleep(2)  # simulate network latency so the pending→processing→completed flow is visible
        return f"""[MOCK] CARE PLAN — {patient.first_name} {patient.last_name} | {patient.mrn}
Medication: {order.medication_name}
Diagnosis: {order.primary_diagnosis}

1. PROBLEM LIST / DRUG THERAPY PROBLEMS
   - Mock DTP 1: Potential drug-disease interaction identified.
   - Mock DTP 2: Dose requires renal adjustment based on records.

2. GOALS (SMART)
   - Achieve target therapeutic outcome within 4 weeks.
   - No adverse effects reported at 2-week follow-up.

3. PHARMACIST INTERVENTIONS / PLAN
   - Initiate {order.medication_name} as prescribed.
   - Counsel patient on administration timing and missed-dose protocol.
   - Coordinate with prescriber for lab monitoring schedule.

4. MONITORING PLAN & LAB SCHEDULE
   - Week 1: Baseline labs (BMP, CBC).
   - Week 4: Follow-up labs + symptom assessment.
   - PRN: Contact clinic if side effects occur.

(This care plan was generated by the mock LLM for development/testing.)"""


_REGISTRY: dict[str, type[BaseLLMService]] = {
    'openai': OpenAIService,
    'mock': MockService,
    # 'claude': ClaudeService,  ← 以后加 Claude 只加这一行
}

def get_llm_service() -> BaseLLMService:
    if os.environ.get('USE_MOCK_LLM', '').lower() == 'true':
        return MockService()
    
    provider = os.environ.get('LLM_PROVIDER', 'openai')
    if provider not in _REGISTRY:
        raise ValueError(f"Unknown LLM provider: '{provider}'")
    return _REGISTRY[provider]()
