import time
import openai
from celery import shared_task
from django.conf import settings

from .models import CarePlan


@shared_task(bind=True, max_retries=3)
def generate_care_plan(self, careplan_id):
    try:
        care_plan = CarePlan.objects.select_related('order__patient').get(id=careplan_id)
    except CarePlan.DoesNotExist:
        return

    care_plan.status = 'processing'
    care_plan.save(update_fields=['status'])

    try:
        order = care_plan.order
        patient = order.patient
        llm_fn = _mock_llm if settings.USE_MOCK_LLM else _call_llm
        care_plan.content = llm_fn(order, patient)
        care_plan.status = 'completed'
        care_plan.save(update_fields=['status', 'content'])
    except Exception as exc:
        care_plan.status = 'pending'
        care_plan.save(update_fields=['status'])
        raise self.retry(exc=exc, countdown=30 * (2 ** self.request.retries))


def _mock_llm(order, patient):
    """Fake LLM: returns a fixed care plan instantly. Enable with USE_MOCK_LLM=true."""
    time.sleep(2)  # simulate network latency so the pending→processing→completed flow is visible
    return f"""[MOCK] CARE PLAN — {patient.first_name} {patient.last_name} | {patient.mrn}
Medication: {order.medication_name}
Diagnosis: {order.primary_diagnosis}

1. PROBLEM LIST / DRUG THERAPY PROBLEMS
   - Mock DTP 1: Potential drug-disease interaction identified.
   - Mock DTP 2: Dose requires renal adjustment based on records.

2. GOALS (SMART)
   - Achieve target therapeutic outcome within 4 weeks.
   - No adverse effects reported at 2-week follow-up.

3. PHARMACIST INTERVENTIONS / PLAN
   - Initiate {order.medication_name} as prescribed.
   - Counsel patient on administration timing and missed-dose protocol.
   - Coordinate with prescriber for lab monitoring schedule.

4. MONITORING PLAN & LAB SCHEDULE
   - Week 1: Baseline labs (BMP, CBC).
   - Week 4: Follow-up labs + symptom assessment.
   - PRN: Contact clinic if side effects occur.

(This care plan was generated by the mock LLM for development/testing.)"""


def _call_llm(order, patient):
    client = openai.OpenAI(api_key=settings.OPENAI_API_KEY)

    prompt = f"""You are a clinical pharmacist. Generate a professional care plan for this patient.

Patient Information:
- Name: {patient.first_name} {patient.last_name}
- MRN: {patient.mrn}
- Primary Diagnosis: {order.primary_diagnosis}
- Medication: {order.medication_name}
- Patient Records: {order.patient_records}

Generate a care plan with these sections:
1. Problem List / Drug Therapy Problems (DTPs)
2. Goals (SMART)
3. Pharmacist Interventions / Plan
4. Monitoring Plan & Lab Schedule

Be specific and clinical."""

    response = client.chat.completions.create(
        model='gpt-4o',
        messages=[{'role': 'user', 'content': prompt}],
        max_tokens=1024,
    )
    return response.choices[0].message.content
